selmaho_to_color = {
    "A" : "#0000FF",
    "BAI" : "#0000FF",
    "BAhE" : "#0000FF",
    "BAhE" : "#0000FF",
    "BE" : "#0000FF",
    "BEI" : "#0000FF",
    "BEhO" : "#0000FF",
    "BIhE" : "#0000FF",
    "BIhI" : "#0000FF",
    "BO" : "#0000FF",
    "BOI" : "#0000FF",
    "BU" : "#0000FF",
    "BY" : "#8090FF",
    "CAI" : "#0000FF",
    "CAhA" : "#0000FF",
    "CEI" : "#0000FF",
    "CEhE" : "#0000FF",
    "CO" : "#0000FF",
    "COI" : "#0000FF",
    "CU" : "#0000FF",
    "CUhE" : "#0000FF",
    "DAhO" : "#0000FF",
    "DOI" : "#0000FF",
    "DOhU" : "#0000FF",
    "FA" : "#0000FF",
    "FAhA" : "#0000FF",
    "FAhO" : "#0000FF",
    "FEhE" : "#0000FF",
    "FEhU" : "#0000FF",
    "FIhO" : "#0000FF",
    "FOI" : "#0000FF",
    "FUhA" : "#0000FF",
    "FUhE" : "#0000FF",
    "FUhO" : "#0000FF",
    "GA" : "#0000FF",
    "GAhO" : "#0000FF",
    "GEhU" : "#0000FF",
    "GI" : "#0000FF",
    "GIhA" : "#0000FF",
    "GOI" : "#0000FF",
    "GOhA" : "#0000FF",
    "GUhA" : "#0000FF",
    "I" : "#0000FF",
    "JA" : "#0000FF",
    "JAI" : "#0000FF",
    "JOI" : "#0000FF",
    "JOhI" : "#0000FF",
    "KE" : "#0000FF",
    "KEI" : "#0000FF",
    "KEhE" : "#0000FF",
    "KI" : "#0000FF",
    "KOhA" : "#0000FF",
    "KU" : "#0000FF",
    "KUhE" : "#0000FF",
    "KUhO" : "#0000FF",
    "LA" : "#0000FF",
    "LAU" : "#0000FF",
    "LAhE" : "#0000FF",
    "LE" : "#0000FF",
    "LEhU" : "#0000FF",
    "LI" : "#0000FF",
    "LIhU" : "#0000FF",
    "LOhO" : "#0000FF",
    "LOhU" : "#0000FF",
    "LU" : "#0000FF",
    "LUhU" : "#0000FF",
    "MAI" : "#0000FF",
    "MAhO" : "#0000FF",
    "MEhU" : "#0000FF",
    "MOI" : "#0000FF",
    "MOhE" : "#0000FF",
    "MOhI" : "#0000FF",
    "NA" : "#C0C0FF",
    "NAI" : "#C0C0FF",
    "NAhE" : "#C0C0FF",
    "NAhU" : "#0000FF",
    "NIhE" : "#0000FF",
    "NIhO" : "#0000FF",
    "NOI" : "#0000FF",
    "NU" : "#0000FF",
    "NUhA" : "#0000FF",
    "NUhI" : "#0000FF",
    "NUhU" : "#0000FF",
    "PA" : "#8080FF",
    "PEhE" : "#0000FF",
    "PEhO" : "#0000FF",
    "PU" : "#C0FFFF",
    "RAhO" : "#0000FF",
    "ROI" : "#0000FF",
    "SA" : "#0000FF",
    "SE" : "#8080FF",
    "SEI" : "#0000FF",
    "SEhU" : "#0000FF",
    "SI" : "#0000FF",
    "SOI" : "#0000FF",
    "SU" : "#0000FF",
    "TAhE" : "#0000FF",
    "TEI" : "#0000FF",
    "TEhU" : "#0000FF",
    "TO" : "#0000FF",
    "TOI" : "#0000FF",
    "TUhE" : "#0000FF",
    "TUhU" : "#0000FF",
    "UI" : "#8080FF",
    "VA" : "#0000FF",
    "VAU" : "#0000FF",
    "VEI" : "#0000FF",
    "VEhA" : "#0000FF",
    "VEhO" : "#0000FF",
    "VIhA" : "#0000FF",
    "VUhO" : "#0000FF",
    "VUhU" : "#0000FF",
    "XI" : "#0000FF",
    "Y" : "#0000FF",
    "ZAhO" : "#0000FF",
    "ZEI" : "#0000FF",
    "ZEhA" : "#0000FF",
    "ZI" : "#0000FF",
    "ZIhE" : "#0000FF",
    "ZO" : "#0000FF",
    "ZOI" : "#0000FF",
    "ZOhU" : "#0000FF",
    "UNCAT" : "#0000FF",
}

selmaho_to_dic = {
    "A": {
        ".a",
        ".e",
        ".o",
        ".u",
    },
    "BAI": {
        "ba'i",
        "bai",
        "bau",
        "be'i",
        "ca'i",
        "cau",
        "ci'e",
        "ci'o",
        "ci'u",
        "cu'u",
        "de'i",
        "di'o",
        "do'e",
        "du'i",
        "du'o",
        "fa'e",
        "fau",
        "fi'e",
        "ga'a",
        "gau",
        "ja'e",
        "ja'i",
        "ji'e",
        "ji'o",
        "ji'u",
        "ka'a",
        "ka'i",
        "kai",
        "ki'i",
        "ki'u",
        "koi",
        "ku'u",
        "la'u",
        "le'a",
        "li'e",
        "ma'e",
        "ma'i",
        "mau",
        "me'a",
        "me'e",
        "mu'i",
        "mu'u",
        "ni'i",
        "pa'a",
        "pa'u",
        "pi'o",
        "po'i",
        "pu'a",
        "pu'e",
        "ra'a",
        "ra'i",
        "rai",
        "ri'a",
        "sau",
        "si'u",
        "ta'i",
        "tai",
        "ti'i",
        "ti'u",
        "tu'i",
        "va'o",
        "va'u",
        "zau",
        "zu'e",
    },
    "BAhE": {
        "ba'e",
        "za'e",
    },
    "BAhE": {
        "ba'e",
        "za'e",
    },
    "BE": {
        "be",
    },
    "BEI": {
        "bei",
    },
    "BEhO": {
        "be'o",
    },
    "BIhE": {
        "bi'e",
    },
    "BIhI": {
        "bi'i",
        "bi'o",
        "mi'i",
    },
    "BO": {
        "bo",
    },
    "BOI": {
        "boi",
    },
    "BU": {
        "bu",
    },
    "BY": {
        ".y'y.",
        "by.",
        "cy.",
        "dy.",
        "fy.",
        "gy.",
        "jy.",
        "ky.",
        "ly.",
        "my.",
        "ny.",
        "py.",
        "ry.",
        "sy.",
        "ty.",
        "vy.",
        "xy.",
        "zy.",
        "lo'a",
        "ge'o",
        "je'o",
        "jo'o",
        "ru'o",
        "na'a",
    },
    "CAI": {
        "cai",
        "sai",
        "ru'e",
        "cu'i",
        "pei",
    },
    "CAhA": {
        "ca'a",
        "ka'e",
        "nu'o",
        "pu'i",
    },
    "CEI": {
        "cei",
    },
    "CEhE": {
        "ce'e",
    },
    "CO": {
        "co",
    },
    "COI": {
        "coi",
        "co'o",
        "ju'i",
        "nu'e",
        "ta'a",
        "pe'u",
        "ki'e",
        "fi'i",
        "be'e",
        "re'i",
        "mu'o",
        "je'e",
        "vi'o",
        "ke'o",
        "fe'o",
        "mi'e",
    },
    "CU": {
        "cu",
    },
    "CUhE": {
        "cu'e",
        "nau",
    },
    "DAhO": {
        "da'o",
    },
    "DOI": {
        "doi",
    },
    "DOhU": {
        "do'u",
    },
    "FA": {
        "fa",
        "fe",
        "fi",
        "fo",
        "fu",
        "fi'a",
        "fai",
    },
    "FAhA": {
        "ca'u",
        "ti'a",
        "zu'a",
        "ga'u",
        "ni'a",
        "ne'i",
        "ru'u",
        "pa'o",
        "ne'a",
        "te'e",
        "re'o",
        "fa'a",
        "to'o",
        "zo'i",
        "ze'o",
        "zo'a",
        "be'a",
        "ne'u",
        "du'a",
        "vu'a",
        "bu'u",
    },
    "FAhO": {
        "fa'o",
    },
    "FEhE": {
        "fe'e",
    },
    "FEhU": {
        "fe'u",
    },
    "FIhO": {
        "fi'o",
    },
    "FOI": {
        "foi",
    },
    "FUhA": {
        "fu'a",
    },
    "FUhE": {
        "fu'e",
    },
    "FUhO": {
        "fu'o",
    },
    "GA": {
        "ga",
        "ge",
        "go",
        "gu",
    },
    "GAhO": {
        "ga'o",
        "ke'i",
    },
    "GEhU": {
        "ge'u",
    },
    "GI": {
        "gi",
    },
    "GIhA": {
        "gi'a",
        "gi'e",
        "gi'o",
        "gi'u",
    },
    "GOI": {
        "pe",
        "po",
        "po'e",
        "po'u",
        "ne",
        "no'u",
    },
    "GOhA": {
        "go'i",
        "go'a",
        "go'u",
        "go'e",
        "go'o",
        "nei",
        "no'a",
        "bu'a",
        "bu'e",
        "bu'i",
        "co'e",
        "mo",
        "du",
    },
    "GUhA": {
        "gu'a",
        "gu'e",
        "gu'o",
        "gu'u",
    },
    "I": {
        "i",
    },
    "JA": {
        "ja",
        "je",
        "jo",
        "ju",
    },
    "JAI": {
        "jai",
    },
    "JOI": {
        "joi",
        "ce",
        "ce'o",
        "jo'u",
        "fa'u",
        "jo'e",
        "ku'a",
        "pi'u",
    },
    "JOhI": {
        "jo'i",
    },
    "KE": {
        "ke",
    },
    "KEI": {
        "kei",
    },
    "KEhE": {
        "ke'e",
    },
    "KI": {
        "ki",
    },
    "KOhA": {
        "mi",
        "do",
        "mi'o",
        "mi'a",
        "ma'a",
        "do'o",
        "ko",
        "ti",
        "ta",
        "tu",
        "di'u",
        "de'u",
        "da'u",
        "ti'e",
        "de'e",
        "da'e",
        "dei",
        "do'i",
        "ko'a",
        "ko'e",
        "ko'i",
        "ko'o",
        "ko'u",
        "fo'a",
        "fo'e",
        "fo'i",
        "fo'o",
        "fo'u",
        "ri",
        "ra",
        "ru",
        "zo'e",
        "zu'i",
        "zi'o",
        "vo'a",
        "vo'e",
        "vo'i",
        "vo'o",
        "vo'u",
        "ma",
        "ke'a",
        "ce'u",
        "da",
        "de",
        "di",
    },
    "KU": {
        "ku",
    },
    "KUhE": {
        "ku'e",
    },
    "KUhO": {
        "ku'o",
    },
    "LA": {
        "la",
    },
    "LAU": {
        "tau",
        "zai",
        "ce'a",
        "lau",
    },
    "LAhE": {
        "la'e",
        "lu'e",
        "tu'a",
        "lu'a",
        "lu'i",
        "lu'o",
        "vu'i",
    },
    "LE": {
        "le",
        "lo",
        "lo'e",
        "loi",
    },
    "LEhU": {
        "le'u",
    },
    "LI": {
        "li",
    },
    "LIhU": {
        "li'u",
    },
    "LOhO": {
        "lo'o",
    },
    "LOhU": {
        "lo'u",
    },
    "LU": {
        "lu",
    },
    "LUhU": {
        "lu'u",
    },
    "MAI": {
        "mai",
        "mo'o",
    },
    "MAhO": {
        "ma'o",
    },
    "MEhU": {
        "me'u",
    },
    "MOI": {
        "moi",
        "mei",
        "si'e",
        "cu'o",
        "va'e",
    },
    "MOhE": {
        "mo'e",
    },
    "MOhI": {
        "mo'i",
    },
    "NA": {
        "na",
        "ja'a",
    },
    "NAI": {
        "nai",
    },
    "NAhE": {
        "na'e",
        "to'e",
        "no'e",
    },
    "NAhU": {
        "na'u",
    },
    "NIhE": {
        "ni'e",
    },
    "NIhO": {
        "ni'o",
    },
    "NOI": {
        "noi",
        "poi",
        "voi",
    },
    "NU": {
        "nu",
        "mu'e",
        "pu'u",
        "zu'o",
        "za'i",
        "ka",
        "ni",
        "du'u",
        "li'i",
        "si'o",
        "su'u",
    },
    "NUhA": {
        "nu'a",
    },
    "NUhI": {
        "nu'i",
    },
    "NUhU": {
        "nu'u",
    },
    "PA": {
        "pa",
        "re",
        "ci",
        "vo",
        "mu",
        "xa",
        "ze",
        "bi",
        "so",
        "no",
        "ma'u",
        "ni'u",
        "pi",
        "fi'u",
        "ra'e",
        "ce'i",
        "ki'o",
        "ci'i",
        "ka'o",
        "pai",
        "te'o",
        "fi'u",
        "ro",
        "so'a",
        "so'e",
        "so'i",
        "so'u",
        "no'o",
        "da'a",
        "rau",
        "du'e",
        "mo'a",
        "dau",
        "fei",
        "gai",
        "jau",
        "rei",
        "vai",
        "pi'e",
        "xo",
        "tu'o",
        "ji'i",
        "su'e",
        "su'o",
        "me'i",
        "za'u",
    },
    "PEhE": {
        "pe'e",
    },
    "PEhO": {
        "pe'o",
    },
    "PU": {
        "pu",
        "ca",
        "ba",
    },
    "RAhO": {
        "ra'o",
    },
    "ROI": {
        "roi",
        "re'u",
    },
    "SA": {
        "sa",
    },
    "SE": {
        "se",
        "te",
        "ve",
        "xe",
    },
    "SEI": {
        "sei",
    },
    "SEhU": {
        "se'u",
    },
    "SI": {
        "si",
    },
    "SOI": {
        "soi",
    },
    "SU": {
        "su",
    },
    "TAhE": {
        "di'i",
        "na'o",
        "ru'i",
        "ta'e",
    },
    "TEI": {
        "tei",
    },
    "TEhU": {
        "te'u",
    },
    "TO": {
        "to",
    },
    "TOI": {
        "toi",
    },
    "TUhE": {
        "tu'e",
    },
    "TUhU": {
        "tu'u",
    },
    "UI": {
        ".ua",
        ".u'a",
        ".ue",
        ".u'e",
        ".ui",
        ".u'i",
        ".ui",
        ".u'o",
        ".uu",
        ".u'u",
        ".o'a",
        ".o'e",
        ".oi",
        ".o'i",
        ".o'o",
        ".o'u",
        ".ii",
        ".i'i",
        ".io",
        ".i'o",
        ".iu",
        ".i'u",
        ".a'a",
        ".a'e",
        ".ai",
        ".a'i",
        ".a'o",
        ".au",
        ".a'u",
        ".e'a",
        ".e'e",
        ".ei",
        ".e'i",
        ".e'o",
        ".e'u",
        ".ia",
        ".i'a",
        ".ie",
        ".i'e",
        "ro'a",
        "ro'e",
        "ro'i",
        "ro'u",
        "re'e",
        "ga'i",
        "le'o",
        "vu'e",
        "se'i",
        "ri'e",
        "fu'i",
        "be'u",
        "se'a",
        "dai",
        "bu'o",
        "ja'o",
        "ca'e",
        "ba'a",
        "su'a",
        "va'i",
        "ti'e",
        "ka'u",
        "se'o",
        "za'a",
        "pe'i",
        "ru'a",
        "ju'a",
        "ku'i",
        "ji'a",
        "si'a",
        "mi'u",
        "po'o",
        "li'a",
        "ba'u",
        "zo'o",
        "sa'e",
        "to'u",
        "do'a",
        "sa'u",
        "pa'e",
        "je'u",
        "ju'o",
        "la'a",
        "ta'o",
        "ra'u",
        "mu'a",
        "zu'u",
        "ke'u",
        "da'i",
        "ki'a",
        "na'i",
        "jo'a",
        "li'o",
        "sa'a",
        "xu",
        "pau",
        "pe'a",
        "bi'u",
        "ge'e",
    },
    "VA": {
        "vi",
        "va",
        "vu",
    },
    "VAU": {
        "vau",
    },
    "VEI": {
        "vei",
    },
    "VEhA": {
        "ve'i",
        "ve'a",
        "ve'u",
        "ve'e",
    },
    "VEhO": {
        "ve'o",
    },
    "VIhA": {
        "vi'i",
        "vi'a",
        "vi'u",
        "vi'e",
    },
    "VUhO": {
        "vu'o",
    },
    "VUhU": {
        "su'i",
        "vu'u",
        "pi'i",
        "te'a",
        "va'a",
        "ju'u",
        "ge'a",
        "gei",
        "pi'a",
        "sa'i",
        "fe'a",
    },
    "XI": {
        "xi",
    },
    "Y": {
        ".y.",
    },
    "ZAhO": {
        "pu'o",
        "ca'o",
        "ba'o",
        "co'a",
        "co'u",
        "mo'u",
        "za'o",
        "co'i",
        "de'a",
        "di'a",
    },
    "ZEI": {
        "zei",
    },
    "ZEhA": {
        "ze'i",
        "ze'a",
        "ze'u",
        "ze'e",
    },
    "ZI": {
        "zi",
        "za",
        "zu",
    },
    "ZIhE": {
        "zi'e",
    },
    "ZO": {
        "zo",
    },
    "ZOI": {
        "zoi",
    },
    "ZOhU": {
        "zo'u",
    },
}

# random helper function
def selm_to_dic(selmaho: str):
    with open("meta/selmaho/" + selmaho + ".txt", "r") as f:
        cmavos = f.read().split("\n")
    line_0 = selmaho + " : {"
    lines = ['    "{0}",'.format(cmavo) for cmavo in cmavos if cmavo != ""]
    line_n1 = "}"
    return line_0 + "\n" + "\n".join(lines) + "\n" + line_n1
    