selmaho_to_dic = {
    "A": {".o", ".a", ".u", ".e"},
    "BAI": {
        "ni'i",
        "ka'i",
        "de'i",
        "di'o",
        "zau",
        "pu'e",
        "be'i",
        "gau",
        "ci'e",
        "la'u",
        "kai",
        "du'o",
        "mu'u",
        "ga'a",
        "ki'u",
        "ba'i",
        "fa'e",
        "pa'a",
        "rai",
        "si'u",
        "ti'i",
        "ku'u",
        "pu'a",
        "fau",
        "ja'e",
        "ci'u",
        "va'o",
        "pi'o",
        "li'e",
        "le'a",
        "ta'i",
        "ji'o",
        "ma'i",
        "pa'u",
        "mau",
        "cau",
        "ma'e",
        "ri'a",
        "mu'i",
        "du'i",
        "ra'a",
        "ca'i",
        "cu'u",
        "tu'i",
        "bau",
        "do'e",
        "sau",
        "ka'a",
        "ji'e",
        "ti'u",
        "me'a",
        "zu'e",
        "me'e",
        "fi'e",
        "koi",
        "ja'i",
        "va'u",
        "ki'i",
        "ji'u",
        "po'i",
        "bai",
        "tai",
        "ci'o",
        "ra'i",
    },
    "BAhE": {"za'e", "ba'e"},
    "BE": {"be"},
    "BEI": {"bei"},
    "BEhO": {"be'o"},
    "BIhE": {"bi'e"},
    "BIhI": {"bi'i", "mi'i", "bi'o"},
    "BO": {"bo"},
    "BOI": {"boi"},
    "BU": {"bu"},
    "BY": {
        "jo'o",
        "jy.",
        "xy.",
        "fy.",
        "lo'a",
        "na'a",
        "py.",
        "sy.",
        "ty.",
        "ge'o",
        "cy.",
        "gy.",
        "ly.",
        "by.",
        "ky.",
        "my.",
        "zy.",
        "ny.",
        "ry.",
        "ru'o",
        "dy.",
        "je'o",
        "vy.",
        ".y'y.",
    },
    "CAI": {"pei", "cu'i", "sai", "ru'e", "cai"},
    "CAhA": {"ca'a", "pu'i", "ka'e", "nu'o"},
    "CEI": {"cei"},
    "CEhE": {"ce'e"},
    "CO": {"co"},
    "COI": {
        "fi'i",
        "coi",
        "re'i",
        "mi'e",
        "mu'o",
        "vi'o",
        "pe'u",
        "je'e",
        "co'o",
        "be'e",
        "ki'e",
        "nu'e",
        "ke'o",
        "ta'a",
        "fe'o",
        "ju'i",
        "jo'au",
    },
    "CU": {"cu"},
    "CUhE": {"nau", "cu'e"},
    "DAhO": {"da'o"},
    "DOI": {"doi"},
    "DOhU": {"do'u"},
    "FA": {"fi", "fi'a", "fe", "fo", "fa", "fu", "fai"},
    "FAhA": {
        "to'o",
        "ne'u",
        "zo'a",
        "vu'a",
        "ti'a",
        "ga'u",
        "ni'a",
        "ru'u",
        "fa'a",
        "ne'a",
        "ze'o",
        "ca'u",
        "pa'o",
        "te'e",
        "zu'a",
        "ne'i",
        "re'o",
        "bu'u",
        "zo'i",
        "be'a",
        "du'a",
    },
    "FAhO": {"fa'o"},
    "FEhE": {"fe'e"},
    "FEhU": {"fe'u"},
    "FIhO": {"fi'o"},
    "FOI": {"foi"},
    "FUhA": {"fu'a"},
    "FUhE": {"fu'e"},
    "FUhO": {"fu'o"},
    "GA": {"go", "gu", "ge", "ga"},
    "GAhO": {"ga'o", "ke'i"},
    "GEhU": {"ge'u"},
    "GI": {"gi"},
    "GIhA": {"gi'o", "gi'u", "gi'e", "gi'a"},
    "GOI": {"no'u", "pe", "ne", "po", "po'u", "po'e", "goi"},
    "GOhA": {
        "mo",
        "go'e",
        "bu'a",
        "go'u",
        "bu'e",
        "nei",
        "du",
        "bu'i",
        "go'i",
        "no'a",
        "go'a",
        "go'o",
        "co'e",
    },
    "GUhA": {"gu'e", "gu'o", "gu'a", "gu'u"},
    "I": {".i"},
    "JA": {"ju", "je", "jo", "ja"},
    "JAI": {"jai"},
    "JOI": {"pi'u", "jo'u", "ku'a", "fa'u", "ce", "joi", "ce'o", "jo'e"},
    "JOhI": {"jo'i"},
    "KE": {"ke"},
    "KEI": {"kei"},
    "KEhE": {"ke'e"},
    "KI": {"ki"},
    "KOhA": {
        "ti'e",
        "ru",
        "mi'a",
        "ra",
        "da'u",
        "di",
        "ko'i",
        "vo'e",
        "do'i",
        "ma",
        "de'e",
        "da",
        "fo'i",
        "vo'i",
        "fo'u",
        "do",
        "ko'e",
        "de",
        "zu'i",
        "di'u",
        "ke'a",
        "fo'e",
        "mi'o",
        "fo'a",
        "zi'o",
        "ta",
        "vo'o",
        "ko",
        "do'o",
        "ti",
        "ko'o",
        "ri",
        "vo'a",
        "ko'a",
        "di'e",
        "zo'e",
        "ce'u",
        "dei",
        "vo'u",
        "fo'o",
        "ma'a",
        "da'e",
        "de'u",
        "tu",
        "mi",
        "ko'u",
    },
    "KU": {"ku"},
    "KUhE": {"ku'e"},
    "KUhO": {"ku'o"},
    "LA": {"la"},
    "LAU": {"lau", "tau", "zai", "ce'a"},
    "LAhE": {"lu'e", "tu'a", "lu'a", "lu'i", "la'e", "vu'i", "lu'o"},
    "LE": {"lo'e", "lo", "le", "ri'oi", "lei", "loi"},
    "LEhU": {"le'u"},
    "LI": {"li"},
    "LIhU": {"li'u"},
    "LOhO": {"lo'o"},
    "LOhU": {"lo'u"},
    "LU": {"lu"},
    "LUhU": {"lu'u"},
    "MAI": {"mai", "mo'o"},
    "MAhO": {"ma'o"},
    "ME" : {"me"},
    "MEhU": {"me'u"},
    "MOI": {"si'e", "cu'o", "mei", "moi", "va'e"},
    "MOhE": {"mo'e"},
    "MOhI": {"mo'i"},
    "NA": {"na", "ja'a"},
    "NAI": {"nai"},
    "NAhE": {"to'e", "no'e", "na'e"},
    "NAhU": {"na'u"},
    "NIhE": {"ni'e"},
    "NIhO": {"ni'o"},
    "NOI": {"poi", "noi", "voi"},
    "NU": {
        "du'u",
        "su'u",
        "za'i",
        "ka",
        "pu'u",
        "zu'o",
        "nu",
        "ni",
        "mu'e",
        "li'i",
        "si'o",
    },
    "NUhA": {"nu'a"},
    "NUhI": {"nu'i"},
    "NUhU": {"nu'u"},
    "PA": {
        "me'i",
        "fi'u",
        "so'e",
        "dau",
        "re",
        "no",
        "za'u",
        "ni'u",
        "so'i",
        "ji'i",
        "da'a",
        "ce'i",
        "su'o",
        "tu'o",
        "mo'a",
        "so'o",
        "ki'o",
        "ci",
        "ze",
        "vo",
        "pi'e",
        "gai",
        "ro",
        "te'o",
        "pi",
        "jau",
        "ma'u",
        "rau",
        "ka'o",
        "ra'e",
        "pai",
        "so",
        "rei",
        "fei",
        "xa",
        "xo",
        "ci'i",
        "su'e",
        "mu",
        "bi",
        "vai",
        "no'o",
        "so'a",
        "pa",
        "du'e",
        "so'u",
    },
    "PEhE": {"pe'e"},
    "PEhO": {"pe'o"},
    "PU": {"ba", "pu", "ca"},
    "RAhO": {"ra'o"},
    "ROI": {"roi", "re'u"},
    "SA": {"sa"},
    "SE": {"se", "xe", "ve", "te"},
    "SEI": {"sei"},
    "SEhU": {"se'u"},
    "SI": {"si"},
    "SOI": {"soi"},
    "SU": {"su"},
    "TAhE": {"ru'i", "di'i", "na'o", "ta'e"},
    "TEI": {"tei"},
    "TEhU": {"te'u"},
    "TO": {"to", "to'i"},
    "TOI": {"toi"},
    "TUhE": {"tu'e"},
    "TUhU": {"tu'u"},
    "UI": {
        "ti'e",
        ".o'i",
        ".o'u",
        "kau",
        "dai",
        "mu'a",
        "vu'e",
        "ri'e",
        ".i'e",
        ".e'e",
        "xu",
        "ka'u",
        ".u'i",
        "to'u",
        "sa'e",
        ".ai",
        "bu'o",
        "bi'u",
        "sa'u",
        ".o'a",
        "se'i",
        ".ei",
        "ro'i",
        "jo'a",
        ".u'e",
        "pe'a",
        "mi'u",
        "pa'e",
        ".au",
        "ba'u",
        ".a'u",
        "ki'a",
        ".oi",
        ".a'e",
        "fu'i",
        "pe'i",
        "ga'i",
        "ro'u",
        ".ii",
        ".iu",
        "ro'a",
        ".i'u",
        ".e'u",
        ".ie",
        ".u'o",
        ".o'e",
        ".ue",
        "do'a",
        ".u'a",
        ".uu",
        "ju'o",
        ".i'a",
        "be'u",
        "le'o",
        ".ua",
        "la'a",
        "ja'o",
        "da'i",
        "na'i",
        ".a'a",
        "ge'e",
        "ba'a",
        ".e'a",
        ".i'i",
        "re'e",
        "ju'a",
        "se'o",
        "li'o",
        ".e'i",
        "zo'o",
        "ku'i",
        "si'a",
        "sa'a",
        "po'o",
        "ru'a",
        "se'a",
        "ro'e",
        "za'a",
        ".a'o",
        ".i'o",
        "va'i",
        ".o'o",
        "ta'o",
        "ra'u",
        ".e'o",
        "ji'a",
        "je'u",
        "li'a",
        "ke'u",
        ".ia",
        ".ui",
        "zu'u",
        "su'a",
        "pau",
        ".a'i",
        ".u'u",
        ".io",
        "ca'e",
    },
    "VA": {"vi", "va", "vu"},
    "VAU": {"vau"},
    "VEI": {"vei"},
    "VEhA": {"ve'a", "ve'u", "ve'e", "ve'i"},
    "VEhO": {"ve'o"},
    "VIhA": {"vi'u", "vi'e", "vi'i", "vi'a"},
    "VUhO": {"vu'o"},
    "VUhU": {
        "vu'u",
        "sa'i",
        "su'i",
        "va'a",
        "pi'i",
        "ju'u",
        "gei",
        "te'a",
        "fe'a",
        "ge'a",
        "pi'a",
    },
    "XI": {"xi"},
    "Y": {".y."},
    "ZAhO": {
        "co'u",
        "za'o",
        "ba'o",
        "ca'o",
        "de'a",
        "di'a",
        "pu'o",
        "co'i",
        "mo'u",
        "co'a",
    },
    "ZEI": {"zei"},
    "ZEhA": {"ze'u", "ze'a", "ze'e", "ze'i"},
    "ZI": {"zu", "zi", "za"},
    "ZIhE": {"zi'e"},
    "ZO": {"zo"},
    "ZOI": {"zoi", "la'o"},
    "ZOhU": {"zo'u"},
}
